### ISSUE TITLE
Bug deleted files

### ISSUE THREAD

**Issue by PenTaist** [SoftLightGames/GIT-Synchronizer#1]
If you delete a file or folder in your github code, this will not delete in destination path.

Fix (deployer.sh) :
1 - Remove all files (destination)
2 - git pull
3 - Copy source files to destination folder
4 (optional) - Delete source files for free space

**Comment by SoftLightGames** [comment]
Ok thx so much, this will be fixed quickly

**Comment by PenTaist** [comment]
Ok :)

**Comment by SoftLightGames** [comment]
Bug has been fixed
